# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o "Do\ hoa.o" MENU.o game.o mainfunc.o
LINKOBJ  = main.o "Do hoa.o" MENU.o game.o mainfunc.o
LIBS     = -L"D:/app code/Dev-Cpp/MinGW64/lib" -L"D:/app code/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lwinmm
INCS     = -I"D:/app code/Dev-Cpp/MinGW64/include" -I"D:/app code/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/app code/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/app code/Dev-Cpp/MinGW64/include" -I"D:/app code/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/app code/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/app code/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

"Do\ hoa.o": Do\ hoa.cpp
	$(CPP) -c "Do hoa.cpp" -o "Do hoa.o" $(CXXFLAGS)

MENU.o: MENU.cpp
	$(CPP) -c MENU.cpp -o MENU.o $(CXXFLAGS)

game.o: game.cpp
	$(CPP) -c game.cpp -o game.o $(CXXFLAGS)

mainfunc.o: mainfunc.cpp
	$(CPP) -c mainfunc.cpp -o mainfunc.o $(CXXFLAGS)
